version: '3.8'

services:
  yois-frontend:
    container_name: yois_frontend
    build: ./frontend
    ports:
      - "6000:3000" # Asegúrate de acceder a http://localhost:6000
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  yois-backend:
    container_name: yois_backend
    build: ./backend
    ports:
      - "6001:9000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - yois-mysql

  yois-mysql:
    container_name: yois_mysql
    image: mysql:8
    restart: always
    ports:
      - "6006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: yois_db
      MYSQL_USER: yois
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
