version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "6000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: yois_db
      MYSQL_USER: yois
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
