name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run tests
      run: |
        cd frontend
        npm test -- --coverage --watchAll=false
        
    - name: Build application
      run: |
        cd frontend
        npm run build
        
    - name: Verify build artifacts
      run: |
        cd frontend
        ls -la build/
        echo "✅ Build artifacts created successfully"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/yoisar_deploy
        chmod 600 ~/.ssh/yoisar_deploy        
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        ssh-keyscan -H -p 2223 92.112.178.62 >> ~/.ssh/known_hosts
        
    - name: Test SSH connection
      run: |
        ssh -p 2223 -i ~/.ssh/yoisar_deploy -o ConnectTimeout=10 ${{ secrets.SERVER_USER }}@92.112.178.62 "echo 'SSH connection successful'"
        
    - name: Deploy to production server
      run: |
        ssh -p 2223 -i ~/.ssh/yoisar_deploy ${{ secrets.SERVER_USER }}@92.112.178.62 << 'EOF'
          cd /www/wwwroot/yoisar.com/app
          ./deploy-prod.sh
        EOF
